// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1dqgbqcwqDob0vio2qqUGODIeHvlWkM8',
    appId: '1:259641700294:web:2d292c72ee616858b1ccc7',
    messagingSenderId: '259641700294',
    projectId: 'chat-app-807d6',
    authDomain: 'chat-app-807d6.firebaseapp.com',
    storageBucket: 'chat-app-807d6.appspot.com',
    measurementId: 'G-24KNR6YTPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqJAYHVArsNtVoag87dKNCM1Lb5wp0eY4',
    appId: '1:259641700294:android:81853ce3829ee377b1ccc7',
    messagingSenderId: '259641700294',
    projectId: 'chat-app-807d6',
    storageBucket: 'chat-app-807d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV41fEtCRoVj0BW1DqG7dftfZBRz4Nzc0',
    appId: '1:259641700294:ios:936a9dfd2d242f56b1ccc7',
    messagingSenderId: '259641700294',
    projectId: 'chat-app-807d6',
    storageBucket: 'chat-app-807d6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV41fEtCRoVj0BW1DqG7dftfZBRz4Nzc0',
    appId: '1:259641700294:ios:936a9dfd2d242f56b1ccc7',
    messagingSenderId: '259641700294',
    projectId: 'chat-app-807d6',
    storageBucket: 'chat-app-807d6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1dqgbqcwqDob0vio2qqUGODIeHvlWkM8',
    appId: '1:259641700294:web:619747d7d93d36bcb1ccc7',
    messagingSenderId: '259641700294',
    projectId: 'chat-app-807d6',
    authDomain: 'chat-app-807d6.firebaseapp.com',
    storageBucket: 'chat-app-807d6.appspot.com',
    measurementId: 'G-19KJY4EQE4',
  );
}
